### ISSUE TITLE
error_log httpd

### ISSUE THREAD

**Issue by elekgeek** [clonemeagain/plugin-autocloser#31]
I am receiving tese lines after isntalling autocloser plugin:

phar:///var/www/html/osTicket/include/plugins/audit.phar/class.audit.php:746
Stack trace:
#0 /var/www/html/osTicket/include/class.signal.php(98): AuditEntry::auditObjectEvent(Object(ConfigItem), Array)
#1 /var/www/html/osTicket/include/class.config.php(124): Signal::send('object.edited', Object(ConfigItem), Array)
#2 /var/www/html/osTicket/include/class.config.php(81): Config->update('last-run', 1592598242)
#3 /var/www/html/osTicket/include/plugins/plugin-autocloser-1.1/class.CloserPlugin.php(188): Config->set('last-run', 1592598242)
#4 /var/www/html/osTicket/include/plugins/plugin-autocloser-1.1/class.CloserPlugin.php(79): CloserPlugin->is_time_to_run(Object(CloserPluginConfig))
#5 /var/www/html/osTicket/include/plugins/plugin-autocloser-1.1/class.CloserPlugin.php(68): CloserPlugin->logans_run_mode()
#6 /var/www/html/osTicket/include/class.signal.php(98): CloserPlugin->{closure}(NULL, Array)
#7 /var/www/html/osTicket/include/class.cron.php(122):  in phar:///var/www/html/osTicket/include/plugins/audit.phar/class.audit.php on line 746

**Comment by ksduster** [comment]
I to have the same results.  My server is IIS 10. I've created a post on the osticket forums for v.1.14.x modifications
`PHP Fatal error:  Uncaught Error: Call to a member function getName() on null in phar://C:/inetpub/wwwroot/helpdesk/include/plugins/audit.phar/class.audit.php:746
Stack trace:
#0 C:\inetpub\wwwroot\helpdesk\include\class.signal.php(98): AuditEntry::auditObjectEvent(Object(ConfigItem), Array)
#1 C:\inetpub\wwwroot\helpdesk\include\class.config.php(124): Signal::send('object.edited', Object(ConfigItem), Array)
#2 C:\inetpub\wwwroot\helpdesk\include\class.config.php(81): Config->update('last-run', 1598211725)
#3 C:\inetpub\wwwroot\helpdesk\include\plugins\autocloser\class.CloserPlugin.php(188): Config->set('last-run', 1598211725)
#4 C:\inetpub\wwwroot\helpdesk\include\plugins\autocloser\class.CloserPlugin.php(79): CloserPlugin->is_time_to_run(Object(CloserPluginConfig))
#5 C:\inetpub\wwwroot\helpdesk\include\plugins\autocloser\class.CloserPlugin.php(68): CloserPlugin->logans_run_mode()
#6 C:\inetpub\wwwroot\helpdesk\include\class.signal.php(98): CloserPlugin->{closure}(NULL, Array)
#7 C:\inetpub\wwwroot\helpdesk\include\class.cro in phar://C:/inetpub/wwwroot/helpdesk/include/plugins/audit.phar/class.audit.php on line 746
`
