### ISSUE TITLE
Issue with OsTicket official plugin for audit.phar

### ISSUE THREAD

**Issue by ksduster** [clonemeagain/plugin-autocloser#34]
Hello,

I found an issue where a fatal error is happening between the autocloser plugin and the official osticket audit plugin.

When both plugins are active I receive the following PHP Fatal error, and stack trace.
Server Info: Microsoft Windows Server 2019
osTicket Version v1.14.3
Web Server Software: Microsoft-IIS/10.0
MySQL Version: 8.0.19
PHP Version: 7.3.15

```
PHP Fatal error: Uncaught Error: Call to a member function getName() on null in phar://C:/inetpub/wwwroot/helpdesk/include/plugins/audit.phar/class.audit.php:746
Stack trace:
#0 C:\inetpub\wwwroot\helpdesk\include\class.signal.php(98): AuditEntry::auditObjectEvent(Object(ConfigItem), Array)
#1 C:\inetpub\wwwroot\helpdesk\include\class.config.php(124): Signal::send('object.edited', Object(ConfigItem), Array)
#2 C:\inetpub\wwwroot\helpdesk\include\class.config.php(81): Config->update('last-run', 1598211725)
#3 C:\inetpub\wwwroot\helpdesk\include\plugins\autocloser\class.CloserPlugin.php(188): Config->set('last-run', 1598211725)
#4 C:\inetpub\wwwroot\helpdesk\include\plugins\autocloser\class.CloserPlugin.php(79): CloserPlugin->is_time_to_run(Object(CloserPluginConfig))
#5 C:\inetpub\wwwroot\helpdesk\include\plugins\autocloser\class.CloserPlugin.php(68): CloserPlugin->logans_run_mode()
#6 C:\inetpub\wwwroot\helpdesk\include\class.signal.php(98): CloserPlugin->{closure}(NULL, Array)
#7 C:\inetpub\wwwroot\helpdesk\include\class.cro in phar://C:/inetpub/wwwroot/helpdesk/include/plugins/audit.phar/class.audit.php on line 746
```

If there is any further information I can provide please let me know.

**Comment by clonemeagain** [comment]
Fun
