### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by nandi96** [clonemeagain/plugin-autocloser#46]
Hi,

I installed the plugin and it is not working.

osticket 1.17.1
Php 8.0
Cron job configured.

**Comment by nandi96** [comment]
[INSERT INTO `ost_config` SET `key` = 'last-run', `value` = 1668609291, `updated` = NOW()]

Duplicate entry 'last-run' for key 'namespace'<br /> <br />
---- Backtrace ----<br />
#0 (root)/include/mysqli.php(207): osTicket->logDBError('DB Error #1062', '[INSERT INTO `o...')<br />
#1 (root)/include/class.orm.php(3482): db_query('INSERT INTO `os...', true, true)<br />
#2 (root)/include/class.orm.php(658): MySqlExecutor->execute()<br />
#3 (root)/include/class.config.php(181): VerySimpleModel->save(true)<br />
#4 (root)/include/class.config.php(114): ConfigItem->save()<br />
#5 (root)/include/class.config.php(124): Config->create('last-run', 1668609291)<br />
#6 (root)/include/class.config.php(89): Config->update('last-run', 1668609291)<br />
#7 (root)/include/plugins/plugin-autocloser-master/class.CloserPlugin.php(188): Config->set('last-run', 1668609291)<br />
#8 (root)/include/plugins/plugin-autocloser-master/class.CloserPlugin.php(79): CloserPlugin->is_time_to_run(Object(CloserPluginConfig))<br />
#9 (root)/include/plugins/plugin-autocloser-master/class.CloserPlugin.php(68): CloserPlugin->logans_run_mode()<br />
#10 (root)/include/class.signal.php(98): CloserPlugin->{closure}(NULL, Array)<br />
#11 (root)/include/class.cron.php(122): Signal::send('cron', NULL, Array)<br />
#12 (root)/include/api.cron.php(19): Cron::run()<br />
#13 (root)/include/api.cron.php(40): CronApiController->run()<br />
#14 (root)/api/cron.php(23): LocalCronApiController::call()<br />
#15 {main}

**Comment by nandi96** [comment]
Continue here: https://github.com/clonemeagain/plugin-autocloser/issues/45
